spring:
  instance:
    hostname: localhost
    prefer-ip-address: true
  application:
    name: sd-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/seat-order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

mybatis:
  type-aliases-package: cn.tedu.sdorder.entity
  mapper-locations: classpath:/mapper/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    io:
      seata: info
    cn.tedu: debug

ribbon:
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  #ribbon的超时时间
#  ReadTimeout: 30000
#  ConnectTimeout: 30000
